name: Release-please

on:
  push:
    branches:
      - main

permissions: write-all

env:
  DOCKER_PATH: ./docker
  DOCKER_IMAGE: 36node/mysql-backup
  HARBOR_REPO: common
  CHART_NAME: mysql-backup-chart

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple

  docker-and-helm:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version tag
        id: get_tag
        # needs.release-please.outputs.tag_name = v1.0.0
        run: echo "VERSION=$(echo "${{ needs.release-please.outputs.tag_name }}" | cut -c 1-)" >> $GITHUB_OUTPUT
      - name: Print tag1
        run: echo "tag=${{ steps.get_tag.outputs.VERSION }}"
      - name: Print tag2
        run: |
          TAG=$(echo "${{ steps.get_tag.outputs.VERSION }}" | sed 's/v\([0-9.]*\).*/\1/')
          echo "tag2=$TAG"
